'use strict';

/**
 * Built-in static question bank — used when no LLM provider is configured
 * or as fallback when an LLM call fails.
 *
 * Questions are tagged by category for report analysis.
 */

const FREE_QUESTIONS = [
  {
    orderIndex: 1,
    category: 'academics',
    questionType: 'single_choice',
    questionText: 'Which subject do you enjoy the most in school?',
    options: [
      { value: 'science', label: 'Science (Physics, Chemistry, Biology)' },
      { value: 'math', label: 'Mathematics' },
      { value: 'commerce', label: 'Commerce & Accounts' },
      { value: 'humanities', label: 'Humanities & Social Studies' },
      { value: 'arts', label: 'Arts & Craft' },
      { value: 'languages', label: 'Languages & Literature' },
    ],
  },
  {
    orderIndex: 2,
    category: 'interests',
    questionType: 'single_choice',
    questionText: 'What kind of activities do you enjoy outside of school?',
    options: [
      { value: 'tech', label: 'Computers, coding, or technology' },
      { value: 'sports', label: 'Sports or fitness' },
      { value: 'music', label: 'Music, singing, or dancing' },
      { value: 'drawing', label: 'Drawing, painting, or design' },
      { value: 'reading', label: 'Reading books or writing stories' },
      { value: 'helping', label: 'Helping or volunteering in the community' },
    ],
  },
  {
    orderIndex: 3,
    category: 'personality',
    questionType: 'single_choice',
    questionText: 'How would you describe yourself best?',
    options: [
      { value: 'analytical', label: 'Analytical — I love solving problems' },
      { value: 'creative', label: 'Creative — I love making new things' },
      { value: 'social', label: 'Social — I love working with people' },
      { value: 'organised', label: 'Organised — I love planning and order' },
      { value: 'adventurous', label: 'Adventurous — I love taking risks' },
      { value: 'caring', label: 'Caring — I love helping others' },
    ],
  },
  {
    orderIndex: 4,
    category: 'goals',
    questionType: 'single_choice',
    questionText: 'What is your biggest career goal?',
    options: [
      { value: 'stability', label: 'Earn a stable and safe income' },
      { value: 'impact', label: 'Make a positive impact on society' },
      { value: 'fame', label: 'Become famous or well-recognised' },
      { value: 'entrepreneur', label: 'Start my own business' },
      { value: 'explore', label: 'Travel and explore the world' },
      { value: 'passion', label: 'Follow my passion, whatever it is' },
    ],
  },
  {
    orderIndex: 5,
    category: 'skills',
    questionType: 'single_choice',
    questionText: 'Which of the following feels most natural to you?',
    options: [
      { value: 'writing', label: 'Writing and explaining ideas' },
      { value: 'building', label: 'Building or fixing things' },
      { value: 'leading', label: 'Leading and organising groups' },
      { value: 'calculating', label: 'Calculating and analysing data' },
      { value: 'performing', label: 'Performing or presenting to an audience' },
      { value: 'researching', label: 'Researching and discovering new knowledge' },
    ],
  },
  {
    orderIndex: 6,
    category: 'academics',
    questionType: 'single_choice',
    questionText: 'How are your academic grades overall?',
    options: [
      { value: 'excellent', label: 'Excellent — I score above 90%' },
      { value: 'good', label: 'Good — I score between 75%–90%' },
      { value: 'average', label: 'Average — I score between 50%–75%' },
      { value: 'working', label: 'Still working on it' },
    ],
  },
  {
    orderIndex: 7,
    category: 'interests',
    questionType: 'multi_choice',
    questionText: 'Which of these career fields sounds interesting to you? (Select all that apply)',
    options: [
      { value: 'engineering', label: 'Engineering & Technology' },
      { value: 'medicine', label: 'Medicine & Healthcare' },
      { value: 'business', label: 'Business & Finance' },
      { value: 'design', label: 'Design, Arts & Media' },
      { value: 'law', label: 'Law & Policy' },
      { value: 'education', label: 'Education & Research' },
      { value: 'defence', label: 'Defence & Government Services' },
      { value: 'sports', label: 'Sports & Fitness' },
    ],
  },
  {
    orderIndex: 8,
    category: 'personality',
    questionType: 'scale',
    questionText: 'How comfortable are you working independently without supervision?',
    options: [
      { value: '1', label: 'Not at all comfortable' },
      { value: '2', label: 'Slightly comfortable' },
      { value: '3', label: 'Moderately comfortable' },
      { value: '4', label: 'Very comfortable' },
      { value: '5', label: 'Completely self-driven' },
    ],
  },
  {
    orderIndex: 9,
    category: 'goals',
    questionType: 'single_choice',
    questionText: 'After Class 12, what are you most likely to do?',
    options: [
      { value: 'college_india', label: 'Apply for college in India (JEE / NEET / others)' },
      { value: 'college_abroad', label: 'Study abroad (USA / UK / Canada / Australia)' },
      { value: 'vocational', label: 'Take a vocational / diploma course' },
      { value: 'work', label: 'Start working / doing internships' },
      { value: 'business', label: 'Start a small business or side project' },
      { value: 'unsure', label: "I'm not sure yet" },
    ],
  },
  {
    orderIndex: 10,
    category: 'skills',
    questionType: 'text',
    questionText: 'In 1-2 sentences, describe what you dream of doing as a career. (No wrong answer!)',
    options: null,
  },
];

const PAID_EXTRA_QUESTIONS = [
  {
    orderIndex: 11,
    category: 'personality',
    questionType: 'multi_choice',
    questionText: 'What motivates you most in life? (Select up to 3)',
    options: [
      { value: 'money', label: 'Financial success and wealth' },
      { value: 'recognition', label: 'Achievement and recognition' },
      { value: 'curiosity', label: 'Learning new things' },
      { value: 'family', label: 'Providing for my family' },
      { value: 'creativity', label: 'Expressing my creativity' },
      { value: 'meaning', label: 'Finding meaning and purpose' },
      { value: 'freedom', label: 'Freedom and flexibility' },
    ],
  },
  {
    orderIndex: 12,
    category: 'skills',
    questionType: 'single_choice',
    questionText: 'When given a complex problem, what is your first instinct?',
    options: [
      { value: 'research', label: 'Research it thoroughly before acting' },
      { value: 'experiment', label: 'Try different solutions and learn by doing' },
      { value: 'discuss', label: 'Discuss it with others to get their input' },
      { value: 'systematic', label: 'Break it into smaller systematic steps' },
      { value: 'intuition', label: 'Go with my gut feeling' },
    ],
  },
  {
    orderIndex: 13,
    category: 'interests',
    questionType: 'single_choice',
    questionText: 'If you could shadow a professional for a day, who would it be?',
    options: [
      { value: 'scientist', label: 'A research scientist in a lab' },
      { value: 'ceo', label: 'A CEO running a company' },
      { value: 'doctor', label: 'A doctor or surgeon' },
      { value: 'artist', label: 'A filmmaker, musician, or artist' },
      { value: 'lawyer', label: 'A lawyer in a courtroom' },
      { value: 'ias', label: 'An IAS officer or government official' },
      { value: 'athlete', label: 'A professional athlete or coach' },
      { value: 'teacher', label: 'A professor or teacher at a top university' },
    ],
  },
  {
    orderIndex: 14,
    category: 'academics',
    questionType: 'multi_choice',
    questionText: 'Which subjects do you find challenging? (They might actually point to hidden strengths)',
    options: [
      { value: 'math', label: 'Mathematics' },
      { value: 'physics', label: 'Physics' },
      { value: 'chemistry', label: 'Chemistry' },
      { value: 'biology', label: 'Biology' },
      { value: 'english', label: 'English or Communication' },
      { value: 'history', label: 'History / Civics' },
      { value: 'economics', label: 'Economics' },
      { value: 'none', label: 'None — I manage well in all subjects' },
    ],
  },
  {
    orderIndex: 15,
    category: 'goals',
    questionType: 'scale',
    questionText: 'How important is earning a high income to your career choice?',
    options: [
      { value: '1', label: 'Not important — I care more about passion' },
      { value: '2', label: 'Slightly important' },
      { value: '3', label: 'Moderately important — I want a balance' },
      { value: '4', label: 'Very important' },
      { value: '5', label: 'Extremely important — income is my top priority' },
    ],
  },
  {
    orderIndex: 16,
    category: 'personality',
    questionType: 'single_choice',
    questionText: 'What kind of work environment would make you happiest?',
    options: [
      { value: 'office', label: 'A structured office with clear processes' },
      { value: 'outdoor', label: 'Outdoors or fieldwork' },
      { value: 'remote', label: 'Remote — work from anywhere' },
      { value: 'hospital', label: 'Hospital, clinic, or social setting' },
      { value: 'startup', label: 'A fast-paced startup' },
      { value: 'creative', label: 'A creative studio or media company' },
    ],
  },
  {
    orderIndex: 17,
    category: 'skills',
    questionType: 'single_choice',
    questionText: 'Which of these skills do you most want to develop?',
    options: [
      { value: 'communication', label: 'Communication and public speaking' },
      { value: 'technical', label: 'Technical / coding / engineering skills' },
      { value: 'leadership', label: 'Leadership and management' },
      { value: 'creative', label: 'Creative and design skills' },
      { value: 'analytical', label: 'Analytical and data interpretation' },
      { value: 'research', label: 'Research and academic writing' },
    ],
  },
  {
    orderIndex: 18,
    category: 'interests',
    questionType: 'text',
    questionText: 'Is there a person (family member, celebrity, leader) whose career you admire? What do you admire about it?',
    options: null,
  },
  {
    orderIndex: 19,
    category: 'goals',
    questionType: 'text',
    questionText: 'What is one thing about your future career that worries or confuses you the most?',
    options: null,
  },
  {
    orderIndex: 20,
    category: 'personality',
    questionType: 'text',
    questionText: 'Describe a moment when you felt truly proud of something you accomplished. What was it, and why did it make you proud?',
    options: null,
  },
];

module.exports = { FREE_QUESTIONS, PAID_EXTRA_QUESTIONS };
