'use strict';
const PDFDocument = require('pdfkit');
const config = require('../../config/config');
const StorageService = require('../storage/StorageService');
const logger = require('../../utils/logger');

// Brand colors
const COLORS = {
  primary: '#1e40af',
  secondary: '#f59e0b',
  accent: '#0d9488',
  dark: '#1e293b',
  muted: '#64748b',
  light: '#f1f5f9',
  white: '#ffffff',
  border: '#e2e8f0',
};

function hexToRgb(hex) {
  const r = parseInt(hex.slice(1, 3), 16);
  const g = parseInt(hex.slice(3, 5), 16);
  const b = parseInt(hex.slice(5, 7), 16);
  return [r, g, b];
}

const PDFService = {
  /**
   * Generate a PDF career report.
   * @param {Object} params
   * @param {Object} params.student - { name, email, age, standard }
   * @param {Object} params.reportContent - structured report from LLM
   * @param {string} params.reportType - 'free' | 'paid'
   * @param {string|null} params.upgradeToken - token for upgrade CTA in free report
   * @returns {{ filename, path }}
   */
  async generate({ student, reportContent, reportType, upgradeToken }) {
    const timestamp = Date.now();
    const safeName = (student.name || 'student').replace(/[^a-zA-Z0-9]/g, '_').slice(0, 20);
    const filename = `report_${safeName}_${timestamp}.pdf`;
    const key = `pdfs/${filename}`;

    const buffer = await new Promise((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50, info: { Title: 'Career Counseling Report', Author: config.company.name } });
      const chunks = [];
      doc.on('data', (chunk) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      if (reportType === 'paid') {
        PDFService._buildPaidReport(doc, student, reportContent, config.company);
      } else {
        PDFService._buildFreeReport(doc, student, reportContent, upgradeToken, config.company);
      }

      doc.end();
    });

    await StorageService.upload(key, buffer);
    logger.debug('PDF uploaded to Spaces', { key });
    return { filename, key };
  },

  // ─── Shared helpers ──────────────────────────────────────────

  _drawHeader(doc, company, reportType) {
    const [pr, pg, pb] = hexToRgb(COLORS.primary);
    doc.rect(0, 0, doc.page.width, 100).fill(`rgb(${pr},${pg},${pb})`);
    doc.fillColor(COLORS.white).fontSize(22).font('Helvetica-Bold')
      .text(company.name, 50, 30);
    doc.fontSize(11).font('Helvetica')
      .text('Student Career Counseling Report', 50, 58);
    const badge = reportType === 'paid' ? '★ PREMIUM REPORT' : 'FREE REPORT';
    const [sr, sg, sb] = hexToRgb(COLORS.secondary);
    doc.rect(doc.page.width - 160, 15, 110, 28).fill(`rgb(${sr},${sg},${sb})`);
    doc.fillColor(COLORS.dark).fontSize(10).font('Helvetica-Bold')
      .text(badge, doc.page.width - 158, 23, { width: 106, align: 'center' });
    doc.moveDown(4);
  },

  _drawSectionTitle(doc, title) {
    const [pr, pg, pb] = hexToRgb(COLORS.primary);
    doc.rect(50, doc.y, doc.page.width - 100, 26).fill(`rgb(${pr},${pg},${pb})`);
    doc.fillColor(COLORS.white).fontSize(12).font('Helvetica-Bold')
      .text(title, 58, doc.y - 20);
    doc.moveDown(1.5);
  },

  _drawBullet(doc, text, indent = 60) {
    const [ar, ag, ab] = hexToRgb(COLORS.accent);
    const y = doc.y;
    doc.circle(indent - 12, y + 5, 3).fill(`rgb(${ar},${ag},${ab})`);
    doc.fillColor(COLORS.dark).fontSize(11).font('Helvetica')
      .text(text, indent, y, { width: doc.page.width - indent - 50 });
    doc.moveDown(0.4);
  },

  _drawStudentCard(doc, student) {
    const [lr, lg, lb] = hexToRgb(COLORS.light);
    doc.rect(50, doc.y, doc.page.width - 100, 70).fill(`rgb(${lr},${lg},${lb})`);
    const cardTop = doc.y - 64;
    doc.fillColor(COLORS.dark).fontSize(14).font('Helvetica-Bold')
      .text(student.name, 65, cardTop + 12);
    doc.fillColor(COLORS.muted).fontSize(10).font('Helvetica')
      .text(`Class: ${student.standard}  |  Age: ${student.age} years  |  ${student.email}`, 65, cardTop + 34);
    doc.fillColor(COLORS.muted).fontSize(10)
      .text(`Report generated by ${config.company.name} on ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, 65, cardTop + 52);
    doc.moveDown(2);
  },

  _drawFooter(doc, company, pageNum) {
    const bottom = doc.page.height - 50;
    const [br, bg, bb] = hexToRgb(COLORS.border);
    doc.moveTo(50, bottom).lineTo(doc.page.width - 50, bottom).stroke(`rgb(${br},${bg},${bb})`);
    doc.fillColor(COLORS.muted).fontSize(9).font('Helvetica')
      .text(`${company.name}  |  ${company.email}  |  ${company.address}`, 50, bottom + 8, { align: 'center', width: doc.page.width - 100 });
  },

  // ─── Free Report ─────────────────────────────────────────────

  _buildFreeReport(doc, student, report, upgradeToken, company) {
    PDFService._drawHeader(doc, company, 'free');
    PDFService._drawStudentCard(doc, student);

    // Summary
    PDFService._drawSectionTitle(doc, '  Your Career Overview');
    doc.fillColor(COLORS.dark).fontSize(11).font('Helvetica')
      .text(report.summary || 'Based on your responses, we have prepared a preliminary overview of your career potential.', 50, doc.y, { width: doc.page.width - 100 });
    doc.moveDown(1.5);

    // Strengths
    PDFService._drawSectionTitle(doc, '  Your Key Strengths');
    (report.strengths || []).forEach((s) => PDFService._drawBullet(doc, s));
    doc.moveDown(1);

    // Career Suggestions (limited in free report)
    PDFService._drawSectionTitle(doc, '  Suggested Career Paths');
    const suggestions = (report.careerSuggestions || []).slice(0, 3);
    suggestions.forEach((s, i) => {
      const [pr, pg, pb] = hexToRgb(COLORS.primary);
      doc.fillColor(`rgb(${pr},${pg},${pb})`).fontSize(12).font('Helvetica-Bold')
        .text(`${i + 1}. ${s.title}`, 60, doc.y);
      doc.fillColor(COLORS.dark).fontSize(10).font('Helvetica')
        .text(s.description, 70, doc.y, { width: doc.page.width - 120 });
      doc.moveDown(0.8);
    });
    doc.moveDown(0.5);

    // Next Steps
    PDFService._drawSectionTitle(doc, '  Recommended Next Steps');
    (report.nextSteps || []).slice(0, 3).forEach((s) => PDFService._drawBullet(doc, s));
    doc.moveDown(1.5);

    // Upgrade CTA
    if (upgradeToken) {
      const upgradeUrl = `${company.website}/upgrade?token=${upgradeToken}`;
      const [sr, sg, sb] = hexToRgb(COLORS.secondary);
      doc.rect(50, doc.y, doc.page.width - 100, 90).fill(`rgb(${sr},${sg},${sb})`);
      const ctaTop = doc.y - 84;
      doc.fillColor(COLORS.dark).fontSize(14).font('Helvetica-Bold')
        .text('🌟 Unlock Your Full Personalized Report — Only ₹499', 65, ctaTop + 10, { width: doc.page.width - 130 });
      doc.fontSize(10).font('Helvetica')
        .text('Get in-depth career analysis, 6+ career paths, personality insights, and a personalised action plan.', 65, ctaTop + 38, { width: doc.page.width - 130 });
      doc.fillColor(COLORS.primary).fontSize(10).font('Helvetica-Bold')
        .text(`Click to Upgrade: ${upgradeUrl}`, 65, ctaTop + 64, { width: doc.page.width - 130, link: upgradeUrl, underline: true });
      doc.moveDown(3);
    }

    PDFService._drawFooter(doc, company, 1);
  },

  // ─── Paid Report ─────────────────────────────────────────────

  _buildPaidReport(doc, student, report, company) {
    PDFService._drawHeader(doc, company, 'paid');
    PDFService._drawStudentCard(doc, student);

    // Summary
    PDFService._drawSectionTitle(doc, '  Executive Summary');
    doc.fillColor(COLORS.dark).fontSize(11).font('Helvetica')
      .text(report.summary || '', 50, doc.y, { width: doc.page.width - 100 });
    doc.moveDown(1.5);

    // Personality Insights
    if (report.personalityInsights) {
      PDFService._drawSectionTitle(doc, '  Personality & Learning Style');
      doc.fillColor(COLORS.dark).fontSize(11).font('Helvetica')
        .text(report.personalityInsights, 50, doc.y, { width: doc.page.width - 100 });
      doc.moveDown(1.5);
    }

    // Interest Pattern
    if (report.interestPattern) {
      PDFService._drawSectionTitle(doc, '  Interest Pattern Analysis');
      doc.fillColor(COLORS.dark).fontSize(11).font('Helvetica')
        .text(report.interestPattern, 50, doc.y, { width: doc.page.width - 100 });
      doc.moveDown(1.5);
    }

    // Strengths
    PDFService._drawSectionTitle(doc, '  Your Key Strengths');
    (report.strengths || []).forEach((s) => PDFService._drawBullet(doc, s));
    doc.moveDown(1);

    // Career Suggestions (all)
    PDFService._drawSectionTitle(doc, '  Personalized Career Paths');
    (report.careerSuggestions || []).forEach((s, i) => {
      if (doc.y > doc.page.height - 160) doc.addPage();
      const [pr, pg, pb] = hexToRgb(COLORS.primary);
      doc.fillColor(`rgb(${pr},${pg},${pb})`).fontSize(13).font('Helvetica-Bold')
        .text(`${i + 1}. ${s.title}   [${s.fit} Fit]`, 55, doc.y);
      doc.fillColor(COLORS.dark).fontSize(10).font('Helvetica')
        .text(s.description, 65, doc.y, { width: doc.page.width - 115 });
      doc.moveDown(0.4);
      const [ar, ag, ab] = hexToRgb(COLORS.accent);
      doc.fillColor(`rgb(${ar},${ag},${ab})`).fontSize(10).font('Helvetica-Bold').text('How to Pursue This Path:', 65, doc.y);
      doc.fillColor(COLORS.dark).font('Helvetica').fontSize(10)
        .text(s.pathway, 65, doc.y, { width: doc.page.width - 115 });
      doc.moveDown(1.2);
    });

    // Academic Pathways
    if (doc.y > doc.page.height - 200) doc.addPage();
    PDFService._drawSectionTitle(doc, '  Academic & Skill Roadmap');
    (report.academicPathways || []).forEach((s, i) => PDFService._drawBullet(doc, `Step ${i + 1}: ${s}`));
    doc.moveDown(1);

    // Next Steps
    PDFService._drawSectionTitle(doc, '  Your Action Plan (Next Steps)');
    (report.nextSteps || []).forEach((s, i) => PDFService._drawBullet(doc, `${i + 1}. ${s}`));
    doc.moveDown(1.5);

    // Motivation
    if (report.motivation) {
      if (doc.y > doc.page.height - 120) doc.addPage();
      PDFService._drawSectionTitle(doc, '  A Message for You');
      const [lr, lg, lb] = hexToRgb(COLORS.light);
      doc.rect(50, doc.y, doc.page.width - 100, 80).fill(`rgb(${lr},${lg},${lb})`);
      const msgTop = doc.y - 74;
      doc.fillColor(COLORS.dark).fontSize(11).font('Helvetica-Oblique')
        .text(`"${report.motivation}"`, 65, msgTop + 10, { width: doc.page.width - 130 });
      doc.moveDown(3);
    }

    // CTA for counseling
    doc.fillColor(COLORS.primary).fontSize(11).font('Helvetica-Bold')
      .text(`Need personalised guidance? Reach us at ${company.email}`, 50, doc.y, { align: 'center', width: doc.page.width - 100 });

    PDFService._drawFooter(doc, company, 1);
  },
};

module.exports = PDFService;
